version: '3.7'

services:
  lancer:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      - DISCORD_BOT_TOKEN
      - DISCORD_CLIENT_ID
      - PGUSER
      - PGHOST=postgres
      - PGPORT=5432
      - PGPASSWORD
      - PGDATABASE
    restart: on-failure:5
    command: npm run prod
  postgres:
    image: docker.io/postgres:14
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
